layout_spectrum: 1
typography_spectrum: 1
color:
  lightness: 0.9409071
  brandStrength: 1
  saturation: 0.845782
  rhythmicContrast: 0.8466055
  brandColors:
    - '#1B161F'
    - '#D3C7C7'
    - '#9A7027'
    - '#4B372D'
    - '#FFDE6A'
name: PRAVAESENCIA.com
