name: PRAVAESENCIA.com
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Prava Esencia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1B161F'
    - '#D3C7C7'
    - '#9A7027'
    - '#4B372D'
    - '#FFDE6A'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
